---
- name: Create config 
  template:
    backup: yes
    owner: root
    group: root
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: slave.cnf.j2, dest: "/etc/my.cnf" }

- name: Enable&Restart mysql
  systemd:
    name: mysqld.service
    state: restarted
    enabled: yes

- name: Get temporary root password from /var/log/mysqld.log
  command: "awk '/A temporary password/ {print $NF}' /var/log/mysqld.log"
  register: "temp_root_password"

- name: Copy root .my.cnf file with temporary password credentials.
  template:
    src: "root.my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: "{{ mysql_root_username }}"
    group: "{{ mysql_root_username }}"
    mode: 0600
  vars:
    password_var: "{{ temp_root_password.stdout }}"

- name: Set root password
  command: 'mysql --connect-expired-password --batch --execute="{{ item }}"'
  with_items:
    - ALTER USER '{{ mysql_root_username }}'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';

- name: Copy root .my.cnf file with password credentials.
  template:
    src: "root.my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: "{{ mysql_root_username }}"
    group: "{{ mysql_root_username }}"
    mode: 0600
  vars:
    password_var: "{{ mysql_root_password }}"



