---
# tasks file for nginx_php

- name: Install Epel
  yum:
    name: epel-release
    state: present


- name: Install Nginx 
  yum:
    name: nginx
    state: present

- name: Install remi-release
  command: "yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm" 

- name: Enable remi-release
  command: "yum-config-manager --enable remi-php73"

- name: Install PHP
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - php
    - php-common 
    - php-opcache 
    - php-mcrypt  
    - php-cli 
    - php-gd 
    - php-curl 
    - php-mysqlnd  
    - php73-php-fpm
    - php73-php-mysqlnd

- name: Config Nginx
  template: 
    owner: root
    group: root
    src: nginx.conf.j2 
    dest: /etc/nginx/nginx.conf

- name: Recursively change ownership of a {{ web_dir }}
  file:
    path: "{{ web_dir }}"
    state: directory
    recurse: yes
    owner: nginx
    group: nginx

- name: Enable&Start php-fpm
  systemd:
    name: php73-php-fpm
    state: started
    enabled: yes

