---
# tasks file for rsyslog

- name: Install rsyslog config
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'crit.conf',dest: '/etc/rsyslog.d' }
    - { src: 'nginx.conf',dest: '/etc/rsyslog.d' }

- name: Permisive SELinux
  command: "setenforce 0"

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted   

