---
# tasks file for config-node


- name: Install packages 
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - ntp
    - nano
    - wget
    - yum-utils
    
- name: Set timezone to Europe/Minsk
  timezone:
    name: Europe/Minsk

- name: Config /etc/hosts
  template:
    backup: yes
    owner: root
    group: root
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: hosts.j2, dest: "/etc/hosts" } 
    - { src: cloud-hosts.j2, dest: "/etc/cloud/templates/hosts.redhat.tmpl" }

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
  

