MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
                },

	}

		

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y wget nano rpmdevtools rpm-build createrepo \
		 yum-utils redhat-lsb-core\
		mkdir ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
		wget -P ~/rpmbuild/SOURCES https://www.apache.org/dist/httpd/httpd-2.4.39.tar.bz2
		wget -P ~/rpmbuild/SOURCES https://www-us.apache.org/dist/apr/apr-1.7.0.tar.bz2
  		wget -P ~/rpmbuild/SOURCES https://www-us.apache.org/dist//apr/apr-util-1.6.1.tar.bz2  
		rpmbuild -tb apr-1.7.0.tar.bz2	
		rpmbuild -tb apr-util-1.6.1.tar.bz2		
	SHELL

      end
  end
end
