MACHINES = {
  :otus => {
        :box_name => "centos/7",
	:ip_addr => '192.168.11.150'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.box_version = "1804.02"
	  box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
            # Подключаем дополнительные диски
            #vb.customize ['createhd', '--filename', second_disk, '--format', 'VDI', '--size', 5 * 1024]
            #vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
	    yum install nano -y
	    vgrename VolGroup00 VG0
	    sed -i 's/VolGroup00/VG0/g' /etc/fstab
	    sed -i 's/VolGroup00/VG0/g' /boot/grub2/grub.cfg
	    mkdir /usr/lib/dracut/modules.d/01test
	    cp /vagrant/*.sh /usr/lib/dracut/modules.d/01test/
	    sed -i 's/rhgb quiet//g' /boot/grub2/grub.cfg
	    dracut -f -v
          SHELL
      end
  end
end

