MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
                },

	}

		

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      	mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
 		yum install epel-release -y && yum install nano wget httpd spawn-fcgi php php-cli mod_fcgid httpd -y
		cp /vagrant/watchlog /etc/sysconfig/watchlog
		cp /vagrant/watchlog.log /var/log/watchlog.log
		cp /vagrant/watchlog.sh /opt/watchlog.sh
		chmod +x /opt/watchlog.sh
		cp /vagrant/watchlog.service /etc/systemd/system/watchlog.service
		cp /vagrant/watchlog.timer /etc/systemd/system/watchlog.timer
		systemctl start watchlog.timer
		cp /vagrant/spawn-fcgi /etc/sysconfig/spawn-fcgi
		cp /vagrant/spawn-fcgi.service /etc/systemd/system/spawn-fcgi.service
		systemctl start spawn-fcgi
		sed -i "9s!/sysconfig/httpd!/sysconfig/httpd-%I!g" /usr/lib/systemd/system/httpd.service
		cp /usr/lib/systemd/system/httpd.service /etc/systemd/system/httpd@first.service
		cp /usr/lib/systemd/system/httpd.service /etc/systemd/system/httpd@second.service
		cp /etc/sysconfig/httpd /etc/sysconfig/httpd-first
		cp /etc/sysconfig/httpd /etc/sysconfig/httpd-second
		sed -i "18iOPTIONS=-f conf/first.conf" /etc/sysconfig/httpd-first
		sed -i "18iOPTIONS=-f conf/second.conf" /etc/sysconfig/httpd-second
		cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/first.conf
		cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/second.conf
		sed -i "32iPidFile /var/run/httpd-second.pid" /etc/httpd/conf/second.conf
		sed -i "s/Listen 80/Listen 81/g" /etc/httpd/conf/second.conf
		systemctl start httpd@first	
		systemctl start httpd@second
	SHELL

      end
  end
end
